<a href="https://colab.research.google.com/github/justeaguey/CE888/blob/Lab3/lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
np.set_printoptions(precision=3)

In [14]:
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv", header = None)

In [15]:
print((data))

       0      1      2      3      4    ...    96     97     98     99     100
0       74  -7.82   8.79  -9.66  -8.16  ...  99.00  -5.63  99.00  99.00  99.00
1      100   4.08  -0.29   6.36   4.37  ...  -2.14   3.06   0.34  -4.32   1.07
2       49  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
3       48  99.00   8.35  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
4       91   8.50   4.61  -4.17  -5.39  ...   1.55   3.11   6.55   1.80   1.60
...    ...    ...    ...    ...    ...  ...    ...    ...    ...    ...    ...
24978  100   0.44   7.43   9.08   2.33  ...   9.03   6.55   8.69   8.79   7.43
24979   91   9.13  -8.16   8.59   9.08  ...  -8.20  -7.23  -8.59   9.13   8.45
24980   39  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24981   37  99.00  99.00  99.00  99.00  ...  99.00  99.00  99.00  99.00  99.00
24982   72   2.43   2.67  -3.98   4.27  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 101 columns]


In [17]:
df = data.drop(columns=[0]) #removes first row as it only holds information on the number of jokes the user has rated, not relevant
print(df)

         1      2      3      4     5    ...    96     97     98     99     100
0      -7.82   8.79  -9.66  -8.16 -7.52  ...  99.00  -5.63  99.00  99.00  99.00
1       4.08  -0.29   6.36   4.37 -2.38  ...  -2.14   3.06   0.34  -4.32   1.07
2      99.00  99.00  99.00  99.00  9.03  ...  99.00  99.00  99.00  99.00  99.00
3      99.00   8.35  99.00  99.00  1.80  ...  99.00  99.00  99.00  99.00  99.00
4       8.50   4.61  -4.17  -5.39  1.36  ...   1.55   3.11   6.55   1.80   1.60
...      ...    ...    ...    ...   ...  ...    ...    ...    ...    ...    ...
24978   0.44   7.43   9.08   2.33  3.20  ...   9.03   6.55   8.69   8.79   7.43
24979   9.13  -8.16   8.59   9.08  0.87  ...  -8.20  -7.23  -8.59   9.13   8.45
24980  99.00  99.00  99.00  99.00 -7.77  ...  99.00  99.00  99.00  99.00  99.00
24981  99.00  99.00  99.00  99.00 -9.71  ...  99.00  99.00  99.00  99.00  99.00
24982   2.43   2.67  -3.98   4.27 -2.28  ...  99.00  99.00  99.00  99.00  99.00

[24983 rows x 100 columns]


In [18]:
df.replace(99, np.nan, inplace=True)
print(df)

        1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24

In [124]:
df.describe()

1             2    ...           99           100
count  16452.000000  18184.000000  ...  10910.000000  9943.000000
mean       0.904573      0.208460  ...     -0.031244     1.354711
std        5.171798      5.597327  ...      5.176806     5.300409
min       -9.950000     -9.950000  ...     -9.950000    -9.950000
25%       -2.670000     -4.420000  ...     -4.170000    -2.330000
50%        1.600000      0.830000  ...      0.290000     2.140000
75%        4.900000      4.820000  ...      3.980000     5.730000
max        9.370000      9.370000  ...      9.370000     9.370000

[8 rows x 100 columns]

In [91]:
arr = df.values

In [126]:
arr[1605][30]

5.58

In [109]:
rated = np.where(arr!=np.isnan(arr))
print(len(rated[0]), rated[1].shape)
print(rated)

2492917 (2492917,)
(array([    0,     0,     0, ..., 24982, 24982, 24982]), array([ 0,  1,  2, ..., 97, 98, 99]))


In [110]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(orig!=np.isnan(orig))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [111]:
new_arr, idx = replace(arr, 0.1)

In [94]:
print(new_arr)

[[-7.82  8.79 -9.66 ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32 99.  ]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ... 99.     nan   nan]
 [  nan   nan   nan ...   nan 99.     nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]


In [47]:
print(idx)

(array([12091, 24163, 19183, ..., 17779,  4222,    97]), array([20, 30,  6, ..., 59, 42, 57]))


In [114]:
n_latent_factors = 4

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [112]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [115]:
num_iter = 100
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

Iteration 0/100:	MSE=1151.321978


KeyboardInterrupt: ignored

In [116]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[14.483, 12.572, 14.123, ..., 21.976, 21.749, 24.574],
       [ 9.138,  8.06 ,  9.297, ..., 13.942, 13.9  , 15.46 ],
       [24.292, 21.436, 23.97 , ..., 36.979, 36.833, 41.752],
       ...,
       [13.068, 11.252, 12.937, ..., 19.813, 19.571, 21.751],
       [24.17 , 21.125, 23.391, ..., 36.558, 36.357, 41.   ],
       [16.85 , 14.849, 17.186, ..., 25.901, 25.676, 29.142]])

In [117]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [118]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

1    ...                         100
0      (-7.82, 14.482722034208338)  ...    (nan, 24.57442282023197)
1        (99.0, 9.138411849163148)  ...  (1.07, 15.459898509043848)
2        (nan, 24.292247295500683)  ...    (nan, 41.75153908488218)
3       (99.0, 16.428247735932782)  ...   (nan, 27.947220017699475)
4        (8.5, 10.963088662932071)  ...   (1.6, 19.222927300264555)
...                            ...  ...                         ...
24978     (0.44, 8.02920026857422)  ...  (7.43, 14.043943416101126)
24979   (99.0, 13.647356707224569)  ...  (99.0, 23.331064189580417)
24980     (nan, 13.06752584702889)  ...   (nan, 21.751188915115904)
24981    (nan, 24.169647121256023)  ...    (nan, 41.00024629474999)
24982   (2.43, 16.849719524883135)  ...   (nan, 29.141604769582006)

[24983 rows x 100 columns]

In [127]:
movies = pd.read_excel("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx")
movies.head()

Movie ID  ...  Factor15
0        11  ... -0.248806
1        12  ...  1.274993
2        13  ... -0.419092
3        14  ... -0.681191
4        22  ... -2.292566

[5 rows x 17 columns]

In [132]:
movies.loc[movies['Factor8'].idxmin()]

Movie ID                     272
Title       Batman Begins (2005)
Factor1                -0.920371
Factor2                -0.694112
Factor3                 0.399493
Factor4                -0.613952
Factor5                 -1.44353
Factor6                -0.688206
Factor7                 0.758949
Factor8                 -1.68634
Factor9                 0.179139
Factor10                -1.09835
Factor11                -1.38819
Factor12               -0.174228
Factor13                 1.79318
Factor14                0.448899
Factor15                0.484224
Name: 30, dtype: object